// Who bought each Commonwealth asset. The Department of Finance's past-sales page names the asset, the
// month and the proceeds but never the purchaser, so this list was gathered by hand on 25 September 2026,
// one sale at a time, from the record that names the buyer: mostly the Audit Office's report on the sale,
// otherwise Hansard, a Parliamentary Library paper or a minister's statement. Each entry carries its source
// so a reader can check it, and `official` is false where only a secondary source could be found. A sale
// with no entry here shows "not traced" on the page rather than a guess.
//
// Matching is by the year of sale and a phrase from the name as Finance writes it, so a rewording of the
// Finance page breaks the match loudly (the buyer disappears) rather than silently attaching to the wrong row.

export type Buyer = {
  year: number; // the year the sale finished, as on the Finance page
  match: string; // a phrase of the Finance name, matched case-insensitively
  buyer: string; // purchaser(s); parts of a split sale separated by semicolons
  sourceUrl: string;
  sourceName: string;
  official: boolean; // true when the source is the ANAO, Parliament, a department or a minister
  note?: string;
};

export const BUYERS: Buyer[] = [
  { year: 1988, match: "Commonwealth Accommodation and Catering", buyer: "Delaware North Companies International and Command Services Corporation (Hawley Group), joint venture",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id:%22media/pressrel/HPR06004806%22",
    sourceName: "Minister for Finance (Peter Walsh) Press Release No. 10/88, 15 March 1988, 'Sale of Commonwealth Accommodation and Catering Services Ltd (CACS)' (ParlInfo)", official: true,
    note: "The release prices the shares at $6.075m; Finance's $14.9m covers the whole transaction." },
  { year: 1988, match: "Defence Service House Corporation Loan", buyer: "Westpac Banking Corporation",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id:%22chamber/hansardr/1991-06-20/0023%22;src1=sm1",
    sourceName: "House of Representatives Hansard, 20 June 1991, 'Defence Service Home Loans' (Mr Filing)", official: true },
  { year: 1989, match: "AMDEL", buyer: "CRA Limited",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id:%22media/pressrel/1659199%22",
    sourceName: "Ministers for Finance and Resources joint Press Release No. 25/89, 23 June 1989, 'Sale of Commonwealth shareholding in Amdel Limited' (ParlInfo)", official: true },
  { year: 1991, match: "Australian Defence Force Home Loan", buyer: "National Australia Bank Limited",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id:%22media/pressrel/HPR04001995%22",
    sourceName: "Minister for Defence Science and Personnel (Gordon Bilney) News Release No. 68/91, 15 May 1991, 'Defence Homeowner starts today' (ParlInfo)", official: true,
    note: "The $42m was the franchise fee for a 15-year exclusive right to provide the subsidised loans." },
  { year: 1991, match: "Commonwealth Housing Loan Assistance", buyer: "ANZ Bank (Australia and New Zealand Banking Group)",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id:%22chamber/hansards/1991-02-13/0158%22",
    sourceName: "Senate Hansard, 13 February 1991, Answers to Questions No. 354 'Commonwealth Home Loan Mortgages' (Minister for Finance via Senator Button)", official: true,
    note: "The Hansard answer records the sale to ANZ; Finance dates completion to June 1991." },
  { year: 1992, match: "Australian Airlines", buyer: "Qantas Airways Limited",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id:%22media/pressrel/2943741%22",
    sourceName: "Minister for Finance (Ralph Willis) Press Release No. 19/92, 14 September 1992, 'Sale of Australian Airlines to Qantas completed' (ParlInfo)", official: true },
  { year: 1993, match: "25% of Qantas", buyer: "British Airways Plc",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id:%22chamber/hansardr/1993-09-29/0002%22",
    sourceName: "House of Representatives Hansard, 29 September 1993, Qantas Sale Amendment Bill 1993 Second Reading", official: true,
    note: "Completed 10 March 1993; the rest of Qantas was floated in 1995." },
  { year: 1993, match: "Snowy Mountains Engineering", buyer: "Tinbury Ltd, a company formed by SMEC staff (employee buyout)",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;db=CHAMBER;id=chamber/hansardr/1993-09-07/0026;query=Id:%22chamber/hansardr/1993-09-07/0070%22",
    sourceName: "House of Representatives Hansard, 7 September 1993, Snowy Mountains Engineering Corporation Limited Sale Bill 1993 Second Reading (Mr Willis, Minister for Finance)", official: true },
  { year: 1994, match: "Moomba-Sydney Pipeline", buyer: "East Australian Pipeline Ltd (EAPL), owned by Australian Gas Light Company (AGL, 51%) and Gasinvest (49%; Nova Corporation of Canada and Petronas)",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;db=CHAMBER;id=chamber/hansardr/1996-09-10/0094;query=Id:%22chamber/hansardr/1996-09-10/0048%22",
    sourceName: "House of Representatives Hansard, 10 September 1996, Question on Notice No. 573 'Australian Pipeline Authority' (Mr Anderson); see also ANAO Audit Report No. 10 1995-96 'Sale of the Moomba to Sydney Gas Pipeline'", official: true,
    note: "The pipeline passed to EAPL on 30 June 1994; the ANAO reported on the sale in 1995-96." },
  { year: 1994, match: "Commonwealth Uranium Stockpile", buyer: "Undisclosed electricity utilities in the United States and Canada; names withheld under confidentiality clauses",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id:%22chamber/hansards/1994-10-13/0160%22",
    sourceName: "Senate Hansard, 13 October 1994, Answers to Questions No. 1691 'Uranium' (Minister for Finance via Senator Robert Ray)", official: true,
    note: "1,814 tonnes for about $60m, for civil power generation." },
  { year: 1995, match: "Aerospace Technologies of Australia", buyer: "Rockwell Systems Australia Pty Ltd (subsidiary of Rockwell International)",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id:%22media/pressrel/5223808%22",
    sourceName: "Joint press release, Deputy PM and Minister for Finance (Kim Beazley) and Minister for Defence (Robert Ray), Min 55/95, 27 June 1995, 'Completion of the sale of ASTA' (ParlInfo)", official: true },
  { year: 1996, match: "Commonwealth Funds Management", buyer: "Commonwealth Bank of Australia (CFM Ltd) and Towers Perrin Forster & Crosby (Total Risk Management)",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id%3A%22chamber%2Fhansardr%2F1998-07-15%2F0149%22",
    sourceName: "House of Representatives Hansard, 15 July 1998, Question on Notice 'Government Privatisations' (answer by Minister for Finance John Fahey), p. 6235", official: true },
  { year: 1997, match: "Avalon Airport", buyer: "Foxerco Pty Ltd (Linfox / Fox family interests)",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id%3A%22chamber%2Fhansardr%2F1998-07-15%2F0149%22",
    sourceName: "House of Representatives Hansard, 15 July 1998, Question on Notice 'Government Privatisations'", official: true },
  { year: 1997, match: "Phase 1 Airports", buyer: "Melbourne: Australia Pacific Airports Corporation, $1,307m; Brisbane: Brisbane Airport Corporation, $1,387m; Perth: Airstralia Development Group, $643m",
    sourceUrl: "https://www.anao.gov.au/sites/default/files/ANAO_Report_1997-98_38.pdf",
    sourceName: "ANAO Audit Report No. 38 1997-98, Sale of Brisbane, Melbourne and Perth Airports", official: true,
    note: "Fifty-year leases from 1 July 1997; consortium members from trade press, not the audit." },
  { year: 1997, match: "DASFLEET", buyer: "Macquarie Fleet Leasing Pty Ltd (wholly owned subsidiary of Macquarie Bank Ltd)",
    sourceUrl: "https://www.anao.gov.au/sites/default/files/anao_report_1998-99_25.pdf",
    sourceName: "ANAO Audit Report No. 25 1998-99, DASFLEET Sale - DAS Business Unit Sales", official: true },
  { year: 1997, match: "Australian Industry Development Corporation", buyer: "Consortium of Babcock & Brown and UBS Australia Ltd (subsidiary of Union Bank of Switzerland)",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id%3A%22chamber%2Fhansardr%2F1998-07-15%2F0149%22",
    sourceName: "House of Representatives Hansard, 15 July 1998, Question on Notice 'Government Privatisations'", official: true,
    note: "Plus the defeasance of $3.2 billion of Commonwealth-guaranteed debt." },
  { year: 1997, match: "Australian National Railways Commission", buyer: "SA Rail: Genesee & Wyoming consortium, $57.4m; Tasrail: Australian Transport Network (Tranz Rail and Wisconsin Central), $22m; Pax Rail: Great Southern Railway consortium, $16m",
    sourceUrl: "https://www.anao.gov.au/sites/default/files/anao_report_1998-99_28.pdf",
    sourceName: "ANAO Audit Report No. 28 1998-99, Sale of SA Rail, Tasrail and Pax Rail", official: true,
    note: "Agreements signed 28 August 1997; the ANAO names all three purchasers." },
  { year: 1997, match: "Department of Administrative Services", buyer: "Asset Services: P&O Asset Services, $18.5m; Works Australia: Gutteridge Haskins & Davey, $4.3m; Australian Property Group: Knight Frank Price Waterhouse, $3.9m; Australian Operational Support Services: Kilpatrick Green, $2.1m; DAS Distribution, Interiors Australia and the Centre for Environmental Management: employee and management buy-outs",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id%3A%22chamber%2Fhansardr%2F1998-07-15%2F0149%22",
    sourceName: "House of Representatives Hansard, 15 July 1998, Question on Notice 'Government Privatisations'; prices from ANAO Audit Report No. 24 1998-99, DAS Business Unit Sales Management (Figure 2.1)", official: true,
    note: "Per-business prices from ANAO Report No. 24 1998-99; DASFLEET was sold separately." },
  { year: 1997, match: "Housing Loans Insurance Corporation", buyer: "GE Capital Services Australia (later GE Mortgage Insurance, Genworth, now Helia)",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id%3A%22chamber%2Fhansardr%2F1998-07-15%2F0149%22",
    sourceName: "House of Representatives Hansard, 15 July 1998, Question on Notice 'Government Privatisations'", official: true,
    note: "The Hansard table shows a lower net figure than Finance's $108m." },
  { year: 1998, match: "Macleod Repatriation Hospital", buyer: "Victorian Government",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id%3A%22chamber%2Fhansardr%2F1998-07-15%2F0149%22",
    sourceName: "House of Representatives Hansard, 15 July 1998, Question on Notice 'Government Privatisations'", official: true },
  { year: 1998, match: "Australian Multimedia Enterprises", buyer: "Allen & Buckeridge Pty Ltd",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id%3A%22chamber%2Fhansardr%2F1998-07-15%2F0149%22",
    sourceName: "House of Representatives Hansard, 15 July 1998, Question on Notice 'Government Privatisations'", official: true,
    note: "The $29.3m was capital AME returned before the sale; the buyer paid a nominal sum for the projects." },
  { year: 1998, match: "Phase 2 Airports", buyer: "Adelaide and Parafield: Adelaide Airport Ltd (Manchester Airport-led), $363.5m; Coolangatta: Queensland Airports Ltd, $103.6m; Canberra: Capital Airport Group, $66.5m; Darwin, Alice Springs and Tennant Creek: Airport Development Group, $110.2m; Hobart: Hobart International Airport Corporation, $35.9m; Launceston: Australia Pacific Airports Corporation, $17.2m; Townsville and Mt Isa: Australian Airports Pty Ltd, $15.9m; Moorabbin: Moorabbin Airport Corporation, $8.2m; Jandakot: Jandakot Airport Holdings, $6.7m; Archerfield: Archerfield Airport Corporation, $3.1m",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id%3A%22chamber%2Fhansardr%2F1998-07-15%2F0149%22",
    sourceName: "House of Representatives Hansard, 15 July 1998, Question on Notice 'Government Privatisations'; lessee companies also in ANAO Audit Report No. 48 1998-99, Phase 2 of the Sales of the Federal Airports (Figure 1.2)", official: true,
    note: "Fourteen airports leased to nine consortia in June 1998; consortium members from trade press, not the audit." },
  { year: 1998, match: "Auscript", buyer: "Employee buy-out team trading as Auscript Ltd (management/employee buy-out)",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id:%22media/pressrel/JM205%22",
    sourceName: "Media Release 30/98, Minister for Finance and Administration (John Fahey), 'AUSCRIPT - preferred buyer', 31 March 1998", official: true,
    note: "Named preferred buyer after a competitive tender; the sale completed in June 1998." },
  { year: 1999, match: "National Transmission Network", buyer: "NTL Australia Pty Ltd (subsidiary of NTL Incorporated, UK/US)",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id:%22media/pressrel/GW506%22",
    sourceName: "Joint Media Release 17/99, Ministers Fahey and Alston, 'National Transmission Network sale', 19 March 1999", official: true,
    note: "NTL Australia was bought by Macquarie in 2002 and became Broadcast Australia." },
  { year: 1999, match: "Australian River Co", buyer: "Liner shipping: Compagnie Generale Maritime (CMA CGM), December 1998; bulk trades: Auscan Self-Unloaders (Intercontinental Ship Management and CSL Group), May 1999; smaller units to Owens Group, Linfox and Chas Kelly Transport",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id:%22media/pressrel/BY706%22",
    sourceName: "Media Release 24/99, Minister for Finance and Administration (John Fahey), 'Sale of Australian River Co. Ltd's bulk shipping business', 4 May 1999 (liner sale: Joint Media Release UM006, 7 December 1998)", official: true },
  { year: 1999, match: "ADI Ltd", buyer: "Transfield Thomson-CSF Pty Ltd (50/50 joint venture of Transfield Holdings and Thomson-CSF, now Thales)",
    sourceUrl: "https://www.aph.gov.au/~/media/wopapub/senate/committee/fadt_ctte/completed_inquiries/1999_02/adi/report/report_pdf.ashx",
    sourceName: "Senate Foreign Affairs, Defence and Trade References Committee, 'The Sale of ADI Limited', February 2000", official: true,
    note: "Settled 29 November 1999; Thales bought out Transfield's half in 2006." },
  { year: 2000, match: "Removals Australia", buyer: "Toll Transport Pty Ltd (Toll Holdings)",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id:%22media/pressrel/LUJ06%22",
    sourceName: "Joint Media Release 76/99, Ministers Fahey and Scott, 'Toll Transport new owners of Removals Australia', 7 December 1999", official: true,
    note: "Toll took over the relocations brokerage on 31 January 2000." },
  { year: 2000, match: "AWRAP", buyer: "No purchaser: converted into the industry-owned Australian Wool Services Ltd, with shares issued free to levy-paying woolgrowers",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id:%22media/pressrel/8J236%22",
    sourceName: "Media Release AFFA00/WT, Minister for Agriculture, Fisheries and Forestry (Warren Truss), 'Industry-owned wool company a step closer', 6 December 2000", official: true,
    note: "Under the Wool Services Privatisation Act 2000; the company later split into Australian Wool Innovation and The Woolmark Company." },
  { year: 2001, match: "Essendon Airport", buyer: "Edgelear Pty Ltd (jointly owned by the Linfox Group and the Becton Group)",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id:%22media/pressrel/YDP46%22",
    sourceName: "Joint Media Release 38/01, Ministers Fahey and Anderson, 'Sale of Essendon Airport', 10 August 2001", official: true,
    note: "Now trades as Essendon Fields." },
  { year: 2002, match: "National Rail Corporation", buyer: "National Rail Consortium (Toll Holdings and Lang Corporation, the Patrick group), later Pacific National",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id:%22media/pressrel/9BU56%22",
    sourceName: "Joint Media Release, Ministers Anderson, Minchin, Batchelor (Vic) and Egan (NSW), 'Combined sale of FreightCorp and National Rail', 31 January 2002", official: true,
    note: "Total transaction $1.172 billion, of which the Commonwealth's share was $220m." },
  { year: 2002, match: "Sydney (Kingsford Smith) Airport", buyer: "Southern Cross Airports Corporation Pty Limited (Macquarie Bank-led consortium)",
    sourceUrl: "https://www.anao.gov.au/sites/default/files/anao_report_2002-2003_43.pdf",
    sourceName: "ANAO Audit Report No. 43 2002-03, 'The Sale of Sydney (Kingsford Smith) Airport'", official: true,
    note: "Completed 28 June 2002; net proceeds $4.216 billion after sale costs." },
  { year: 2003, match: "Sydney Basin Airports", buyer: "BaCH Airports Consortium (sponsored by the Commonwealth Bank, the James Fielding Group and Toll Holdings)",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id:%22media/pressrel/TS6B6%22",
    sourceName: "Media Release 43/2003, Minister for Finance and Administration (Nick Minchin), 'Sydney basin airports sale completed', 16 December 2003", official: true,
    note: "Selected 14 November 2003, completed 15 December 2003." },
  { year: 2004, match: "ComLand", buyer: "Lend Lease, through LDD (Comland) Pty Ltd",
    sourceUrl: "https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id:%22media/pressrel/78RC6%22",
    sourceName: "Media Release 40/04, Minister for Finance and Administration (Nick Minchin), 'ComLand sale completed', 4 June 2004", official: true,
    note: "Agreed price $165m; Finance nets it to $139.7m after ComLand's debt." },
];

export function buyerFor(sale: { year: number; name: string }): Buyer | null {
  const name = sale.name.toLowerCase();
  return BUYERS.find((b) => b.year === sale.year && name.includes(b.match.toLowerCase())) ?? null;
}
